# Generated by Django 3.2.15 on 2022-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан ли текущий пользователь на этого пользователя'),
        ),
    ]
